[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixelthon"
version = "0.1.0"
description = "Библиотека для создания красивых GUI за секунды"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "Ваше Имя" }]